version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "neo4j/SupDev1234"
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck: # ← attend que Bolt réponde
      test:
        [
          "CMD-SHELL",
          "cypher-shell -u $${NEO4J_USER:-neo4j} -p $${NEO4J_PASSWORD:-SupDev1234} 'RETURN 1' || exit 1",
        ]
      interval: 10s
      start_period: 20s
      retries: 10

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    depends_on: # démarre quand les services existent
      - redis
      - mongo
      - neo4j
    restart: on-failure # retry jusqu’à ce que Neo4j soit prêt

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest 
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend
